spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
  datasource:
    name: Spring-QuicklyStart
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: JHA
    password: 220717
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
# MinIO
minio:
  endpoint: http://169.254.64.130:9000/
  access-key: admin
  secret-key: jha220717
  bucket-name: jha-test
server:
  port: 10086
logging:
  level.org.springframework.jdbc.support.JdbcTransactionManager: debug

